# Generated by Django 4.2.11 on 2024-05-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
    ]
