# Generated by Django 4.2.11 on 2024-05-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_city_user_country_user_ip_user_org_user_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='status',
        ),
    ]
