# Generated by Django 4.2.11 on 2024-07-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_onetimepassword_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
    ]
