# Generated by Django 4.2.11 on 2024-05-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_managecard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managecard',
            name='card_pin',
            field=models.CharField(max_length=500),
        ),
    ]
